(()=>{
'use strict';
const DATA=window.COURSE_DATA;
const PAGES=DATA.pages;
const TOTAL=PAGES.length;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORAGE_KEY='tc_training_v2_sealed';
const QA_SESSION='tc_training_v2_qa';
const PEPPER='TC-EDU-V2::F5-TRAINING::2026-08'; // deterrence only; static sites cannot provide server-grade secrecy.
const interactionKinds=new Set(['scenario','phrases','reportPractice','discordPractice','quiz']);
const state={current:0,maxUnlocked:0,audioDone:new Set(),interactionDone:new Set(),completed:new Set(),activated:false,qa:sessionStorage.getItem(QA_SESSION)==='1',activeSeconds:0,audio:null,speechToken:0,qaArm:false,qaClicks:0,qaClickAt:0,qaBuffer:'',quizOrder:null};

// ---------- practical sealed progress storage ----------
const enc=new TextEncoder(), dec=new TextDecoder();
const b64=u=>btoa(String.fromCharCode(...u));
const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function getKey(){
  if(!crypto?.subtle) return null;
  const digest=await crypto.subtle.digest('SHA-256',enc.encode(PEPPER));
  return crypto.subtle.importKey('raw',digest,{name:'AES-GCM'},false,['encrypt','decrypt']);
}
async function saveState(){
  if(state.qa) return;
  const payload=JSON.stringify({v:2,current:state.current,maxUnlocked:state.maxUnlocked,audioDone:[...state.audioDone],interactionDone:[...state.interactionDone],completed:[...state.completed],activeSeconds:state.activeSeconds});
  try{
    const key=await getKey();
    if(key){const iv=crypto.getRandomValues(new Uint8Array(12));const ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(payload)));localStorage.setItem(STORAGE_KEY,JSON.stringify({iv:b64(iv),ct:b64(ct)}));}
    else localStorage.setItem(STORAGE_KEY,btoa(unescape(encodeURIComponent(payload))));
  }catch(_){/* progress saving failure should not stop training */}
}
async function loadState(){
  try{
    const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;
    let payload='';
    const key=await getKey();
    if(key){const box=JSON.parse(raw);const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(box.iv)},key,unb64(box.ct));payload=dec.decode(pt)}
    else payload=decodeURIComponent(escape(atob(raw)));
    const s=JSON.parse(payload);if(s.v!==2)throw 0;
    state.current=Math.max(0,Math.min(TOTAL-1,+s.current||0));
    state.maxUnlocked=Math.max(0,Math.min(TOTAL-1,+s.maxUnlocked||0));
    state.audioDone=new Set((s.audioDone||[]).filter(x=>Number.isInteger(x)&&x>=0&&x<TOTAL));
    state.interactionDone=new Set((s.interactionDone||[]).filter(x=>Number.isInteger(x)&&x>=0&&x<TOTAL));
    state.completed=new Set((s.completed||[]).filter(x=>Number.isInteger(x)&&x>=0&&x<TOTAL));
    state.activeSeconds=Math.max(0,+s.activeSeconds||0);
    if(state.current>state.maxUnlocked)state.current=state.maxUnlocked;
  }catch(_){localStorage.removeItem(STORAGE_KEY)}
}

// Remove hash/query based navigation. This app intentionally has no /1page style route.
try{if(location.hash||location.search)history.replaceState(null,'',location.pathname)}catch(_){}
window.addEventListener('hashchange',()=>{try{history.replaceState(null,'',location.pathname)}catch(_){}});
window.addEventListener('popstate',()=>{try{history.replaceState(null,'',location.pathname)}catch(_){}});

// ---------- helpers ----------
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2600)}
function groupLabel(page){return page.group||'교육 과정'}
function pageHead(page,subtitle){return `<div class="page-head"><div><span class="eyebrow">${esc(groupLabel(page))} · ${String(page.id).padStart(2,'0')}</span><h1>${esc(page.title)}</h1><p class="subtitle">${subtitle||page.short||''}</p></div><div class="mentor-note"><img src="assets/boradori-generated.png" alt="보라돌이"><div><span>교육 안내</span><p>나레이션을 끝까지 들은 뒤 화면의 기준과 실습을 순서대로 확인하십시오.</p></div></div></div>`}
function ruleCards(items){return `<div class="card-grid">${items.map(x=>`<article class="rule-card"><div class="rule-num">${String(x.n).padStart(2,'0')}</div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}</div>`}
function shot(src,caption,focus=[]){return `<figure class="edu-shot"><div class="edu-shot-frame"><img src="${src}" alt="${esc(caption)}">${focus.map(f=>`<span class="focus" style="left:${f[0]}%;top:${f[1]}%;width:${f[2]}%;height:${f[3]}%"><em>${esc(f[4])}</em></span>`).join('')}</div><figcaption><span>${esc(caption)}</span><button class="zoom-btn" data-src="${src}">확대 보기</button></figcaption></figure>`}
function lockOverlay(){return `<div class="interaction-lock" id="interactionLock"><div class="lock-card"><div class="lock-icon">▣</div><b>음성 교육을 먼저 완료하십시오.</b><p>이 페이지의 나레이션이 끝나면 실습이 자동으로 활성화됩니다. 재생 중에는 답안을 입력할 수 없습니다.</p></div></div>`}
function interactionWrap(html){return `<div class="interaction-wrap">${lockOverlay()}<div id="interactionBody">${html}</div></div>`}
function formatTime(sec){sec=Math.floor(sec);return [Math.floor(sec/3600),Math.floor(sec%3600/60),sec%60].map(x=>String(x).padStart(2,'0')).join(':')}
function isInteractive(p=PAGES[state.current]){return interactionKinds.has(p.kind)}
function audioSatisfied(i=state.current){return state.qa||state.audioDone.has(i)}
function interactionSatisfied(i=state.current){return state.qa||!isInteractive(PAGES[i])||state.interactionDone.has(i)}
function pageSatisfied(i=state.current){return audioSatisfied(i)&&interactionSatisfied(i)}
function effectiveMax(){return state.qa?TOTAL-1:state.maxUnlocked}
function markInteractionDone(){state.interactionDone.add(state.current);tryCompleteCurrent();saveState();renderLock();updateNext()}
function tryCompleteCurrent(){if(pageSatisfied()){state.completed.add(state.current);if(state.current<TOTAL-1)state.maxUnlocked=Math.max(state.maxUnlocked,state.current+1);saveState();renderNav();updateNext()}}

// ---------- renderers ----------
function renderHero(page){return `<article class="page hero"><div class="hero-inner"><section class="hero-copy"><span class="eyebrow">THE CUSTOM · CORPORATE TRAINING</span><h1>더커스텀<br><span>교육 매뉴얼 · 2차</span></h1><p class="lead">업무 기준을 단순히 읽는 데 그치지 않고, 모든 설명을 청취한 뒤 사례 판단과 실무 검증을 완료하는 단계형 교육 과정입니다.</p><div class="hero-metrics"><div class="hero-metric"><span>교육 화면</span><b>${TOTAL}단계</b></div><div class="hero-metric"><span>최종 평가</span><b>20문항</b></div><div class="hero-metric"><span>예상 이수</span><b>60분+</b></div></div><div class="callout"><b>이수 원칙</b><br>각 페이지의 나레이션을 끝까지 듣기 전에는 다음 단계가 열리지 않습니다. 실습 페이지는 나레이션 종료 후 실습까지 통과해야 완료됩니다.</div><div class="button-row" style="margin-top:18px"><button class="cta violet" id="startCourse">교육 시작 및 음성 재생</button></div></section><section class="hero-side"><img src="assets/boradori-generated.png" alt="더커스텀 교육 안내 캐릭터 보라돌이"><div class="speech-card"><b>보라돌이 · 교육 안내</b><p>본 교육은 업무 기준을 동일하게 적용하기 위한 정규 과정입니다. 설명과 실습을 순서대로 완료해 주십시오.</p></div></section></div></article>`}
function renderOverview(page){const cards=[['01','기본 수칙','26개 운영 기준과 예외 조건'],['02','경고·보상','경고 14개 기준과 보상 제도'],['03','견인·표준 멘트','현장 판단과 표준 문구'],['04','인턴 교육','콜·판매·제작·무전·공지'],['05','인트라넷·제작','보고서 입력과 제작 기준'],['06','현장 시스템·평가','태블릿·디스코드·20문항']];return `<article class="page">${pageHead(page,'설명 청취 → 사례형 점검 → 실무 입력 → 종합 평가 순서로 진행합니다.')}<div class="overview-grid">${cards.map(c=>`<section class="overview-card"><span class="num">${c[0]}</span><h3>${c[1]}</h3><p>${c[2]}</p></section>`).join('')}</div><div class="divider"></div><div class="process"><div class="step"><b>STEP 1</b><span>페이지 나레이션 전체 청취</span></div><div class="arrow">→</div><div class="step"><b>STEP 2</b><span>표·카드·강조 영역 확인</span></div><div class="arrow">→</div><div class="step"><b>STEP 3</b><span>실습이 있는 경우 전 문항 통과</span></div><div class="arrow">→</div><div class="step"><b>STEP 4</b><span>다음 단계 자동 잠금 해제</span></div></div><div class="callout warn" style="margin-top:16px"><b>직접 주소 접근 차단</b><br>이 과정은 한 개의 교육 화면 안에서만 페이지가 전환됩니다. URL에 페이지 번호를 추가해 단계를 건너뛰는 방식은 지원하지 않습니다.</div></article>`}
function renderRules(page){const body=ruleCards(page.items);const content=page.image?`<div class="visual-layout"><div>${body}</div><div>${shot(page.image,'더커스텀 사유지 위치와 경계 확인')}<div class="callout" style="margin-top:12px"><b>적용 순서</b><br>현재 위치 → 업무 종류 → 예외 조건 → 필요한 보고 또는 공지 순으로 확인하십시오.</div></div></div>`:body;return `<article class="page">${pageHead(page,'번호별 운영 기준을 읽고 예외 조건과 처리 순서를 함께 구분하십시오.')}${content}</article>`}
function renderWarnings(page){return `<article class="page">${pageHead(page,'경고 사유와 처리 수위를 정확히 연결해 숙지하십시오.')}<div class="callout danger"><b>누적 기준</b><br>구두경고 3회 → 내부경고 1회 · 내부경고 2회 → 해임 기준</div><div class="table" style="margin-top:14px"><div class="tr head"><span>번호</span><span>경고 사유</span><span>처리 기준</span></div>${page.items.map(x=>`<div class="tr"><b>${String(x.n).padStart(2,'0')}</b><span>${esc(x.title)}</span><strong>${esc(x.penalty)}</strong></div>`).join('')}</div>${page.items&&page.items[0]&&page.items[0].n===8?'<div class="callout warn" style="margin-top:14px"><b>추가 판단 기준</b><br>이외의 문제는 고위직 및 간부직이 판단합니다. 인턴 기간 중 문제 발생 시 즉시 해임될 수 있으며, 매뉴얼에 없다는 이유로 상식적으로 이해하기 어려운 행동을 정당화할 수 없습니다. 의문이 있으면 행동 전에 간부 또는 고위직에게 DM으로 확인합니다.</div>':''}</article>`}
function renderMetrics(page){if(page.metrics==='reward')return `<article class="page">${pageHead(page,'지급 주기, 중복 제한, 선택 보상을 함께 확인하십시오.')}<div class="metrics"><div class="metric"><span>인센티브 기준</span><b>7 : 3</b><small>지급 기준</small></div><div class="metric"><span>2주 실적 1등</span><b>룰렛 티켓</b><small>보고서 작성·판매 각 1등</small></div><div class="metric"><span>장부 누적 200건</span><b>5억 또는 경고 삭감</b><small>구두경고 1회 삭감 중 선택</small></div><div class="metric"><span>매주 토요일 저녁</span><b>주간 지급</b><small>스테이크·델바·진통제</small></div></div><div class="panel"><h3>2주 실적 보상 조건</h3><p>한 달에 한 번만 참여할 수 있으며 중복 참여는 불가능합니다. 동일인이 보고서 작성 실적과 판매 실적에서 모두 1등이더라도 보상 상품은 한 종류 한 개만 지급하는 기준이 적용됩니다.</p></div></article>`;return `<article class="page">${pageHead(page,'교육 인정 조건과 두 가지 선택 보상을 구분하십시오.')}<div class="subgrid"><div class="panel"><h3>교육 인정 조건</h3><p>인턴 교육은 주임 이상의 직급부터 진행할 수 있습니다. 교육을 시작한 담당자는 중간에 다른 사원에게 넘길 수 없으며 본인이 끝까지 마무리해야 1건으로 누적됩니다.</p></div><div class="panel"><h3>인턴 교육 2건 완료</h3><div class="metrics" style="grid-template-columns:1fr 1fr;margin:0"><div class="metric"><span>선택 A</span><b>구두경고 1회 삭감</b></div><div class="metric"><span>선택 B</span><b>30억</b></div></div></div></div></article>`}
function renderTowing(page){return `<article class="page">${pageHead(page,'견인 전 위치, RP 진행 여부, 집행 요청, 공지 예외를 순서대로 확인하십시오.')}<div class="process"><div class="step"><b>01</b><span>견인 종료까지 무전기·디스코드 참여 + 팩션 차량</span></div><div class="arrow">→</div><div class="step"><b>02</b><span>RP 구역 내부·입구 주변 진행 여부 확인</span></div><div class="arrow">→</div><div class="step"><b>03</b><span>즉시 견인 예외 또는 일반 120초 공지 판단</span></div></div><div class="subgrid" style="margin-top:14px"><div class="panel"><h3>견인 불가·주의</h3><p>필드 RP와 스토리 RP 참여 차량은 견인할 수 없습니다. 게릴라 RP 범위를 확인하고 죽음 시작부터 종료까지 인근 차량을 견인하지 않습니다.</p></div><div class="panel"><h3>즉시 처리·사후 처리</h3><p>공무원·스태프 집행 콜은 공지 없이 즉시 견인할 수 있습니다. 실수로 차량을 견인한 경우 차주에게 500만원을 지급합니다. 메인광장·메인차고·뉴비존·콜 받은 타 팩션 사유지는 즉시 견인 가능합니다.</p></div></div></article>`}
function renderPhrases(page){return `<article class="page">${pageHead(page,'여섯 표준 문구를 모두 직접 열어 확인해야 이 단원이 완료됩니다.')} ${interactionWrap(`<div class="tabs" id="phraseTabs">${page.phrases.map((p,i)=>`<button class="tab ${i===0?'active':''}" data-i="${i}">${esc(p.title)}</button>`).join('')}</div><div class="phrase-box" id="phraseBox">${esc(page.phrases[0].text)}</div><div class="button-row" style="margin-top:12px"><button class="cta secondary" id="phraseNext">다음 문구 →</button><span class="counter-badge" id="phraseCount">확인 1 / 6</span></div><div class="feedback show bad" id="phraseFeedback">아직 확인하지 않은 문구가 있습니다.</div>`)}</article>`}
function renderIntern(page){const content=ruleCards(page.items);let img='';if(page.image){const focus=page.image.includes('tablet')?[[4.5,10,65,38,'콜 정보 확인']]:[];img=shot(page.image,page.image.includes('tablet')?'태블릿 콜 정보 확인':'차량 배치 및 사유지 위치 확인',focus)}return `<article class="page">${pageHead(page,'인턴이 단독 업무를 수행하기 전 반드시 확인해야 하는 실무 기준입니다.')}<div class="visual-layout"><div>${content}</div><div>${img}<div class="callout" style="margin-top:12px"><b>연결해서 기억하기</b><br>출근 상태, 팩션 이동수단, 콜 사유, 판매 제한, 결제, 무전, 공지 확인은 한 번의 업무 흐름에서 동시에 확인될 수 있습니다.</div></div></div></article>`}
function renderReportGuide(page){return `<article class="page">${pageHead(page,'고객 정보 → 판매 물품·수량 → 보고서 작성 순서를 화면과 함께 확인하십시오.')}<div class="visual-layout"><div>${shot(page.image,'더커스텀 인트라넷 거래 보고서 작성 화면',[[6.2,24.4,89.5,8.2,'고유번호·닉네임'],[6.2,47.5,89.5,18.7,'제품·수량'],[63.5,18,21.5,5.2,'보고서 작성']])}</div><div><div class="panel"><h3>작성 기준</h3><div class="process" style="flex-direction:column"><div class="step"><b>1</b><span>상대방 고유번호와 닉네임 정확히 작성</span></div><div class="step"><b>2</b><span>판매한 제품 종류와 수량 입력</span></div><div class="step"><b>3</b><span>긴급 수리도구 하루 10개·기한 4일 이하 판매 불가 확인</span></div><div class="step"><b>4</b><span>최종 보고서 작성 버튼으로 완료</span></div></div></div></div></div><div class="process" style="margin-top:14px"><div class="step"><b>A</b><span>콜 수락·방문 손님 확인</span></div><div class="arrow">→</div><div class="step"><b>B</b><span>인트라넷 장부 작성</span></div><div class="arrow">→</div><div class="step"><b>C</b><span>결제 요청</span></div><div class="arrow">→</div><div class="step"><b>D</b><span>물품 전달</span></div></div></article>`}
function renderReportPractice(page){return `<article class="page">${pageHead(page,'가상 거래 상황을 보고 입력값과 처리 순서를 정확히 검증하십시오.')} ${interactionWrap(`<div class="practice-split"><div class="form-shell"><div class="form-title"><div><small>THE CUSTOM LEDGER</small><b>거래 보고서 작성</b></div></div><div class="form-grid"><div class="field"><label>고유번호</label><input id="rId" placeholder="고유번호"></div><div class="field"><label>닉네임</label><input id="rNick" placeholder="닉네임"></div><div class="field full"><label>제품 종류</label><select id="rProduct"><option value="">선택</option><option>긴급 수리 도구</option><option>전문 수리 도구</option><option>방탄타이어 12시간</option><option>방탄타이어 6시간</option></select></div><div class="field"><label>수량</label><input id="rQty" type="number" min="1" max="10"></div><div class="field"><label>처리 순서</label><select id="rOrder"><option value="">선택</option><option value="good">장부 작성 → 결제 요청 → 물품 전달</option><option value="wrong1">결제 요청 → 물품 전달 → 장부 작성</option><option value="wrong2">물품 전달 → 장부 작성 → 결제 요청</option></select></div></div><button class="cta violet" id="reportSubmit" style="width:100%;margin-top:14px">보고서 작성 및 검증</button></div><div><div class="panel"><h3>교육용 가상 상황</h3><p>야간 출동 중 고객 장비의 긴급 점검이 필요하여 긴급 수리 도구 1개를 제공했습니다. 해당 물품은 판매 가능 기간을 충족한다고 가정합니다.</p><div class="info-table" style="margin-top:12px"><div class="info-key">고유번호</div><div class="info-value">1070-P</div><div class="info-key">닉네임</div><div class="info-value">엔진 헌터</div><div class="info-key">제품 종류</div><div class="info-value">긴급 수리 도구</div><div class="info-key">수량</div><div class="info-value">1개</div></div></div><div id="reportFeedback" class="feedback"></div></div></div>`)}</article>`}
function renderCraft(page){return `<article class="page">${pageHead(page,'거래상에서 재료를 구매한 뒤 제작대에서 품목별 재료와 판매 제한을 확인합니다.')}<div class="image-grid">${shot('assets/material-vendor.png','사유지 내부 정비소 거래상')}${shot('assets/workbench.png','정비소 제작대')}${shot('assets/material-shop.png','정비소 거래상 재료 목록')}${shot('assets/crafting-ui.png','정비소 용품 제작 화면',[[2.6,25.7,42.6,17.4,'제작 품목'],[78.6,10.2,19.2,29,'제작 대기열']])}</div><div class="recipe-grid" style="margin-top:14px">${page.recipes.map(r=>`<div class="recipe"><b>${esc(r.name)}</b><p>${esc(r.recipe)}</p><span class="pill ${r.policy.includes('금지')?'red':r.policy.includes('전용')?'green':''}">${esc(r.policy)}</span></div>`).join('')}</div><div class="callout warn" style="margin-top:14px"><b>제작 수량</b><br>제작대에서는 한 번에 최대 2개까지 제작할 수 있습니다.</div></article>`}
function renderTablet(page){return `<article class="page">${pageHead(page,'별도의 태블릿 실습 없이 콜 확인과 완료 처리에 필요한 화면만 숙지합니다.')}<div class="image-grid">${shot('assets/tablet-call.png','태블릿 알림 및 콜 정보 화면',[[4.8,13,62.5,36.5,'콜 위치·요청자·사유']])}${shot('assets/tablet-settings.png','태블릿 설정 화면',[[2,46,66,21,'퀵알림 설정']])}</div><div class="process" style="margin-top:14px"><div class="step"><b>1</b><span>콜 위치·요청자·사유 확인</span></div><div class="arrow">→</div><div class="step"><b>2</b><span>부정확한 사유면 빠른 답변으로 정정 요청</span></div><div class="arrow">→</div><div class="step"><b>3</b><span>팩션 이동수단으로 출동</span></div><div class="arrow">→</div><div class="step"><b>4</b><span>업무 완료 후 닫기 처리</span></div></div><div class="callout" style="margin-top:14px"><b>알림 수락 불가</b><br>퀵알림 사용 상태와 태블릿 설정을 확인합니다.</div></article>`}
function renderDiscordGuide(page){return `<article class="page">${pageHead(page,'디스코드 PTT와 인게임 무전 키를 구분해 설정합니다.')}<div class="visual-layout"><div>${shot('assets/discord-settings.png','디스코드 음성 및 비디오 설정',[[34.2,5.5,50,8.9,'입력 방식'],[62.5,54.8,22,6.4,'PTT 단축키']])}</div><div class="panel"><h3>설정 기준</h3><p>음성 및 비디오 메뉴에서 눌러서 말하기를 활성화하고 단축키를 지정합니다. 인게임 무전과 디스코드 눌러서 말하기 키는 서로 다르게 설정합니다.</p><div class="divider"></div><div class="info-table"><div class="info-key">인게임 무전 접속</div><div class="info-value">L 키</div><div class="info-key">채널</div><div class="info-value">77.77</div><div class="info-key">비밀번호</div><div class="info-value">7777</div><div class="info-key">말하기</div><div class="info-value">Caps Lock</div></div></div></div></article>`}
function renderDiscordPractice(page){return `<article class="page">${pageHead(page,'눌러서 말하기 활성화와 키 충돌 여부를 직접 검증하십시오.')} ${interactionWrap(`<div class="panel"><label class="check-row"><input type="checkbox" id="pttEnabled"> 디스코드 눌러서 말하기 활성화</label><div class="ptt-panel"><div class="key-field"><label>인게임 무전 키</label><input id="gameKey" class="key-capture" readonly placeholder="클릭 후 키 입력"></div><div class="key-field"><label>디스코드 PTT 키</label><input id="discordKey" class="key-capture" readonly placeholder="클릭 후 키 입력"></div></div><button class="cta violet" id="pttTest" style="width:100%;margin-top:14px">설정 검증</button><div id="pttFeedback" class="feedback"></div></div>`)}</article>`}
function renderReview(page){return `<article class="page">${pageHead(page,'20문항 평가 직전, 숫자·예외·업무 순서를 마지막으로 정리합니다.')}<div class="metrics"><div class="metric"><span>일반 견인 공지</span><b>120초</b></div><div class="metric"><span>영상 보관</span><b>최소 4일</b></div><div class="metric"><span>휴가 1회</span><b>최대 10일</b></div><div class="metric"><span>월 휴가</span><b>20일 초과 주의</b></div></div><div class="subgrid"><div class="panel"><h3>경고·접속·판매</h3><p>구두경고 3회 → 내부경고 1회, 내부경고 2회 → 해임. 월 10일 이하 접속은 해임 기준. 수리키트 하루 최대 10개, 유통기한 4일 이하 판매 불가.</p></div><div class="panel"><h3>무전·제작·장부</h3><p>무전 L / 77.77 / 7777 / Caps Lock. 제작대 1회 최대 2개. 장부는 콜·방문 확인 → 장부 → 결제 → 물품 전달 순서.</p></div></div><div class="callout warn" style="margin-top:14px"><b>평가 전략</b><br>선택지 하나가 규정의 일부만 맞더라도 다른 조건이 틀리면 정답이 아닙니다. 위치·상태·예외·수량·순서를 끝까지 비교하십시오.</div></article>`}
function renderQuiz(page){const order=state.quizOrder||(state.quizOrder=[...Array(page.quiz.length).keys()].sort(()=>Math.random()-.5));return `<article class="page">${pageHead(page,'모든 20문항을 답한 뒤 제출할 수 있으며 18문항 이상 정답이면 수료합니다.')} ${interactionWrap(`<div class="quiz-grid" id="quizGrid">${order.map((idx,pos)=>{const q=page.quiz[idx];return `<section class="quiz-q" data-qi="${idx}"><div class="quiz-q-head"><b>Q${String(pos+1).padStart(2,'0')}</b><span>${esc(q.q)}</span></div>${q.opts.map((o,oi)=>`<label class="quiz-opt"><input type="radio" name="quiz_${idx}" value="${oi}"> ${esc(o)}</label>`).join('')}</section>`}).join('')}</div><div class="quiz-summary"><div><span class="counter-badge" id="quizAnswered">응답 0 / 20</span><div id="quizFeedback" class="feedback"></div></div><button class="cta violet" id="quizSubmit">최종 답안 제출</button></div>`)}</article>`}
function renderComplete(page){return `<article class="page"><div class="completion"><div><div class="complete-mark">✓</div><span class="eyebrow">TRAINING COMPLETE</span><h1>더커스텀 교육 수료</h1><p>필수 나레이션, 중간 실습, 보고서 입력, 설정 검증, 20문항 종합 평가를 모두 완료했습니다.</p><div class="callout good"><b>업무 적용 원칙</b><br>해석이 필요한 상황은 임의로 판단하지 말고 고위직 또는 간부직에게 확인하고, 내부공지를 지속적으로 확인해 최신 운영 기준을 반영하십시오.</div></div></div></article>`}
function renderScenario(page){const set=DATA.scenarios[page.scenarioSet];return `<article class="page">${pageHead(page,'모든 사례를 맞혀야 실습이 완료됩니다. 오답은 바로 수정해 다시 제출할 수 있습니다.')} ${interactionWrap(`<div class="scenario-list" id="scenarioList">${set.map((q,qi)=>`<section class="scenario-card" data-qi="${qi}"><div class="scenario-title"><b>${String(qi+1).padStart(2,'0')}</b><span>${esc(q[0])}</span></div><div class="choice-grid">${q[1].map((o,oi)=>`<button class="choice" data-oi="${oi}">${esc(o)}</button>`).join('')}</div></section>`).join('')}</div><div class="scenario-actions"><button class="cta violet" id="scenarioSubmit">전체 답안 검증</button></div><div id="scenarioFeedback" class="feedback"></div>`)}</article>`}
function renderPage(page){switch(page.kind){case'hero':return renderHero(page);case'overview':return renderOverview(page);case'rules':return renderRules(page);case'warnings':return renderWarnings(page);case'metrics':return renderMetrics(page);case'towing':return renderTowing(page);case'phrases':return renderPhrases(page);case'intern':return renderIntern(page);case'reportGuide':return renderReportGuide(page);case'reportPractice':return renderReportPractice(page);case'craft':return renderCraft(page);case'tabletInfo':return renderTablet(page);case'discordGuide':return renderDiscordGuide(page);case'discordPractice':return renderDiscordPractice(page);case'review':return renderReview(page);case'quiz':return renderQuiz(page);case'complete':return renderComplete(page);case'scenario':return renderScenario(page);default:return `<article class="page">${pageHead(page,'')}</article>`}}

function renderNav(){const nav=$('#nav');let last='';nav.innerHTML=PAGES.map((p,i)=>{const head=p.group!==last?`<div class="nav-group">${esc(p.group)}</div>`:'';last=p.group;const locked=i>effectiveMax();return `${head}<button class="nav-item ${i===state.current?'active':''}" data-i="${i}"><span class="nav-num">${String(i+1).padStart(2,'0')}</span><span class="nav-label"><b>${esc(p.title)}</b><small>${esc(p.short)}</small></span>${state.qa||state.completed.has(i)?'<span class="nav-done">✓</span>':locked?'<span class="nav-lock">•</span>':''}</button>`}).join('');$$('.nav-item',nav).forEach(b=>b.onclick=()=>{const i=+b.dataset.i;if(i<=effectiveMax())go(i);else showToast('앞선 교육 단계를 먼저 완료하십시오.')})}
function updateTop(){const n=state.current+1;$('#progressLabel').textContent=`${n} / ${TOTAL}`;$('#progressFill').style.width=`${n/TOTAL*100}%`;$('#pageCounter').textContent=`${n} / ${TOTAL}`;$('#pageKicker').textContent=`${groupLabel(PAGES[state.current]).toUpperCase()} · ${String(n).padStart(2,'0')}`;$('#elapsedTime').textContent=formatTime(state.activeSeconds)}
function updateVoice(){const strip=$('#voiceStrip'),label=$('#voiceState'),re=$('#replayBtn');strip.classList.remove('playing','done');if(audioSatisfied()){strip.classList.add('done');label.textContent=state.qa?'QA 모드 · 청취 검증 해제':'나레이션 청취 완료';re.disabled=false}else if(state.activated){strip.classList.add('playing');label.textContent='현재 페이지 나레이션 재생 중';re.disabled=true}else{label.textContent='교육 시작 대기';re.disabled=true}}
function renderLock(){const l=$('#interactionLock');if(!l)return;l.classList.toggle('hidden',audioSatisfied())}
function updateNext(){const b=$('#nextBtn');if(state.current===TOTAL-1){b.disabled=true;b.textContent='교육 수료 완료';return}const a=audioSatisfied(),inter=interactionSatisfied();b.classList.toggle('ready',a&&inter);b.disabled=!(a&&inter);if(!a)b.textContent='나레이션 완료 후 이동';else if(!inter)b.textContent='실습 완료 후 이동';else b.textContent='다음 단계 →'}
function render(){stopNarration();const p=PAGES[state.current];$('#viewport').innerHTML=renderPage(p);updateTop();renderNav();updateVoice();renderLock();updateNext();$('#prevBtn').disabled=state.current===0;bindPage();if(state.activated&&!audioSatisfied()&&p.kind!=='complete')playNarration();saveState()}
function go(i){if(i<0||i>=TOTAL)return;if(i>effectiveMax()){showToast('직접 이동할 수 없습니다. 앞 단계를 완료하십시오.');return}state.current=i;state.quizOrder=null;render();$('#viewport').scrollTop=0}
function next(){if(!pageSatisfied()){showToast(!audioSatisfied()?'나레이션을 끝까지 청취해야 합니다.':'현재 페이지의 실습을 완료해야 합니다.');return}tryCompleteCurrent();if(state.current<TOTAL-1){state.current++;state.quizOrder=null;render()}}
function prev(){if(state.current>0){state.current--;state.quizOrder=null;render()}}

// ---------- narration gate ----------
function stopNarration(){state.speechToken++;if(state.audio){try{state.audio.pause();state.audio.src=''}catch(_){}state.audio=null}if('speechSynthesis'in window)try{speechSynthesis.cancel()}catch(_){} }
function finishNarration(pageIndex,token){if(token!==state.speechToken||state.current!==pageIndex)return;state.audioDone.add(pageIndex);updateVoice();renderLock();tryCompleteCurrent();updateNext();saveState();showToast('나레이션 청취가 완료되었습니다.')}
function splitSpeech(text){const sentences=text.match(/[^.!?。！？]+[.!?。！？]?/g)||[text];const out=[];let cur='';for(const s of sentences){if((cur+s).length>190&&cur){out.push(cur.trim());cur=''}cur+=s}if(cur.trim())out.push(cur.trim());return out}
function browserSpeak(text,pageIndex,token){if(!('speechSynthesis'in window)){showToast('브라우저 TTS를 사용할 수 없습니다. MP3 음성을 등록하십시오.');return}const chunks=splitSpeech(text);let idx=0;const speakNext=()=>{if(token!==state.speechToken||state.current!==pageIndex)return;if(idx>=chunks.length){finishNarration(pageIndex,token);return}const u=new SpeechSynthesisUtterance(chunks[idx++]);u.lang='ko-KR';u.rate=.92;u.pitch=.98;u.onend=speakNext;u.onerror=(e)=>{if(e.error==='canceled'||e.error==='interrupted')return;speakNext()};speechSynthesis.speak(u)};speakNext()}
function playNarration(force=false){const p=PAGES[state.current];if(p.kind==='complete'){state.audioDone.add(state.current);updateVoice();return}if(!state.activated)return;if(audioSatisfied()&&!force){updateVoice();return}stopNarration();const pageIndex=state.current,token=state.speechToken;$('#voiceStrip').classList.add('playing');$('#voiceState').textContent='현재 페이지 나레이션 재생 중';const path=`audio/page-${String(pageIndex+1).padStart(2,'0')}.mp3`;const a=new Audio(path);state.audio=a;let fallback=false;const useFallback=()=>{if(fallback||token!==state.speechToken)return;fallback=true;state.audio=null;$('#voiceState').textContent='브라우저 TTS로 교육 음성 재생 중';browserSpeak(p.narration,pageIndex,token)};a.addEventListener('ended',()=>finishNarration(pageIndex,token),{once:true});a.addEventListener('error',useFallback,{once:true});a.play().catch(useFallback)}

// ---------- page interactions ----------
function bindPage(){
  $$('.zoom-btn').forEach(b=>b.onclick=()=>{const z=$('#zoom');z.querySelector('img').src=b.dataset.src;z.classList.add('show')});
  const start=$('#startCourse');if(start)start.onclick=()=>{state.activated=true;playNarration(true);start.disabled=true;start.textContent='음성 교육 진행 중';updateVoice()};
  if(PAGES[state.current].kind==='scenario')bindScenario();
  if(PAGES[state.current].kind==='phrases')bindPhrases();
  if(PAGES[state.current].kind==='reportPractice')bindReport();
  if(PAGES[state.current].kind==='discordPractice')bindDiscord();
  if(PAGES[state.current].kind==='quiz')bindQuiz();
}
function bindScenario(){const set=DATA.scenarios[PAGES[state.current].scenarioSet];$$('.scenario-card').forEach((card,qi)=>{$$('.choice',card).forEach(btn=>btn.onclick=()=>{if(!audioSatisfied())return;$$('.choice',card).forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');card.dataset.sel=btn.dataset.oi})});$('#scenarioSubmit').onclick=()=>{if(!audioSatisfied())return;let correct=0,unanswered=0;$$('.scenario-card').forEach((card,qi)=>{card.classList.remove('correct','wrong');const sel=card.dataset.sel;if(sel==null){unanswered++;return}const ok=+sel===set[qi][2];card.classList.add(ok?'correct':'wrong');$$('.choice',card).forEach(x=>{x.classList.remove('correct','wrong');if(+x.dataset.oi===set[qi][2])x.classList.add('correct');else if(x.classList.contains('selected'))x.classList.add('wrong')});if(ok)correct++});const f=$('#scenarioFeedback');f.className='feedback show '+(correct===set.length?'good':'bad');f.textContent=unanswered?`미응답 ${unanswered}개가 있습니다. 모든 사례에 답하십시오.`:correct===set.length?`전 ${set.length}개 사례를 정확히 판정했습니다.`:`${correct} / ${set.length}개 정답입니다. 표시된 사례를 다시 확인하십시오.`;if(correct===set.length){markInteractionDone();showToast('사례형 실습을 통과했습니다.')}}}
function bindPhrases(){const page=PAGES[state.current];const seen=new Set(state.interactionDone.has(state.current)?page.phrases.map((_,i)=>i):[0]);const tabs=$$('#phraseTabs .tab');const refresh=()=>{const n=seen.size;$('#phraseCount').textContent=`확인 ${n} / ${page.phrases.length}`;const f=$('#phraseFeedback');if(n===page.phrases.length){f.className='feedback show good';f.textContent='표준 문구 6종을 모두 확인했습니다.';markInteractionDone()}else{f.className='feedback show bad';f.textContent=`아직 ${page.phrases.length-n}개 문구를 확인해야 합니다.`}};tabs.forEach(t=>t.onclick=()=>{if(!audioSatisfied())return;tabs.forEach(x=>x.classList.remove('active'));t.classList.add('active');const i=+t.dataset.i;seen.add(i);$('#phraseBox').textContent=page.phrases[i].text;refresh()});$('#phraseNext').onclick=()=>{if(!audioSatisfied())return;const i=tabs.findIndex(x=>x.classList.contains('active'));tabs[(i+1)%tabs.length].click()};refresh()}
function bindReport(){$('#reportSubmit').onclick=()=>{if(!audioSatisfied())return;const errs=[];if($('#rId').value.trim().toUpperCase()!=='1070-P')errs.push('고유번호');if($('#rNick').value.trim()!=='엔진 헌터')errs.push('닉네임');if($('#rProduct').value!=='긴급 수리 도구')errs.push('제품 종류');if(+$('#rQty').value!==1)errs.push('수량');if($('#rOrder').value!=='good')errs.push('처리 순서');const f=$('#reportFeedback');if(errs.length){f.className='feedback show bad';f.innerHTML=`불일치 항목: <b>${errs.join(', ')}</b>. 사례와 업무 순서를 다시 확인하십시오.`}else{f.className='feedback show good';f.textContent='검증 완료. 고객 정보, 제품, 수량, 처리 순서가 모두 일치합니다.';markInteractionDone();showToast('보고서 실습을 통과했습니다.')}}}
let keyTarget=null;
function bindDiscord(){$$('.key-capture').forEach(x=>x.onclick=()=>{if(!audioSatisfied())return;keyTarget=x;x.value='키 입력 대기 중…'});$('#pttTest').onclick=()=>{if(!audioSatisfied())return;const f=$('#pttFeedback'),g=$('#gameKey').dataset.key||'',d=$('#discordKey').dataset.key||'';if(!$('#pttEnabled').checked){f.className='feedback show bad';f.textContent='눌러서 말하기를 활성화하십시오.';return}if(!g||!d){f.className='feedback show bad';f.textContent='두 단축키를 모두 지정하십시오.';return}if(g===d){f.className='feedback show bad';f.textContent='두 키가 동일합니다. 인게임과 디스코드 키를 서로 다르게 지정하십시오.';return}f.className='feedback show good';f.textContent='검증 완료. PTT 활성화와 단축키 분리가 확인되었습니다.';markInteractionDone();showToast('디스코드 설정 실습을 통과했습니다.')}}
function bindQuiz(){const page=PAGES[state.current];const updateCount=()=>{let n=0;for(const q of page.quiz)if($(`input[name="quiz_${page.quiz.indexOf(q)}"]:checked`))n++;$('#quizAnswered').textContent=`응답 ${n} / ${page.quiz.length}`};$$('#quizGrid input').forEach(i=>i.onchange=updateCount);$('#quizSubmit').onclick=()=>{if(!audioSatisfied())return;let answered=0,score=0,miss=[];page.quiz.forEach((q,idx)=>{const s=$(`input[name="quiz_${idx}"]:checked`),box=$(`.quiz-q[data-qi="${idx}"]`);box.classList.remove('correct','wrong');if(!s)return;answered++;const ok=+s.value===q.a;if(ok)score++;else miss.push((state.quizOrder?state.quizOrder.indexOf(idx):idx)+1);box.classList.add(ok?'correct':'wrong')});const f=$('#quizFeedback');if(answered<page.quiz.length){f.className='feedback show bad';f.textContent=`아직 ${page.quiz.length-answered}문항이 미응답입니다. 모든 문항에 답해야 제출할 수 있습니다.`;return}const pass=score>=DATA.meta.passScore;f.className='feedback show '+(pass?'good':'bad');f.innerHTML=`<b>${score} / ${page.quiz.length}</b> · ${pass?'수료 기준을 충족했습니다.':`수료 기준은 ${DATA.meta.passScore}문항입니다. 오답 문항 번호: ${miss.join(', ')}`}`;if(pass){markInteractionDone();showToast('최종 평가를 통과했습니다.')}else showToast('기준 미달입니다. 관련 단원을 복습한 뒤 다시 응시하십시오.')};updateCount()}

// ---------- global controls ----------
$('#nextBtn').onclick=()=>{if(!state.activated&&state.current===0&&!state.qa){showToast('먼저 교육 시작 버튼을 선택하십시오.');return}next()};
$('#prevBtn').onclick=prev;
$('#replayBtn').onclick=()=>{if(!state.activated){state.activated=true}playNarration(true)};
$('#voiceStrip').onclick=e=>{if(e.target.id==='replayBtn')return;if(!state.activated){state.activated=true;playNarration(true);updateVoice()}};
$('#resetBtn').onclick=()=>{if(confirm('교육 진행도를 모두 초기화하시겠습니까?')){localStorage.removeItem(STORAGE_KEY);sessionStorage.removeItem(QA_SESSION);location.reload()}};
$('#zoom').onclick=e=>{if(e.target===$('#zoom')||e.target.tagName==='BUTTON')$('#zoom').classList.remove('show')};

document.addEventListener('keydown',e=>{
  // hidden QA input: no visible field or prompt.
  if(state.qaArm){if(/^\d$/.test(e.key)){state.qaBuffer=(state.qaBuffer+e.key).slice(-5);if(state.qaBuffer.length===5)checkQaBuffer()}}
  if(keyTarget){e.preventDefault();const k=e.code||e.key;keyTarget.dataset.key=k;keyTarget.value=k;keyTarget=null;return}
  if(e.target.matches('input,textarea,select'))return;
  if(e.key==='ArrowLeft')prev();
  if(e.key==='ArrowRight')next();
});


async function checkQaBuffer(){
  try{
    const dig=await crypto.subtle.digest('SHA-256',enc.encode(state.qaBuffer));
    const hex=[...new Uint8Array(dig)].map(b=>b.toString(16).padStart(2,'0')).join('');
    if(hex==='d119aab7bc5c0823d29df1fa368bc56a6f6e333fc680a24ff533e8eb7922bfaa')activateQa();
  }catch(_){
    // Fallback deliberately avoids any visible password input.
    const nums=[49,48,56,48,52];
    if([...state.qaBuffer].every((c,i)=>c.charCodeAt(0)===nums[i]))activateQa();
  }
}

function activateQa(){state.qa=true;state.qaArm=false;state.qaBuffer='';sessionStorage.setItem(QA_SESSION,'1');stopNarration();render();if(!$('#qaBadge')){const d=document.createElement('div');d.id='qaBadge';d.className='qa-badge';d.textContent='QA MODE';document.body.appendChild(d)}showToast('QA 테스트 모드가 활성화되었습니다.')}
$('#devTrigger').addEventListener('click',()=>{const now=Date.now();if(now-state.qaClickAt>4500)state.qaClicks=0;state.qaClickAt=now;state.qaClicks++;if(state.qaClicks>=5){state.qaClicks=0;state.qaArm=true;state.qaBuffer='';setTimeout(()=>{state.qaArm=false;state.qaBuffer=''},9000)}});

// active learning time only while tab is visible
setInterval(()=>{if(!document.hidden){state.activeSeconds++;$('#elapsedTime').textContent=formatTime(state.activeSeconds);if(state.activeSeconds%15===0)saveState()}},1000);

(async function init(){await loadState();if(state.qa){const d=document.createElement('div');d.id='qaBadge';d.className='qa-badge';d.textContent='QA MODE';document.body.appendChild(d)}$('#bootScreen').style.display='none';$('#app').hidden=false;render()})();
})();
